### PR TITLE
Code Player(JS bin clone)

### PR DESCRIPTION
**Pull request by Tejaswini-052**
JS Bin allows you to directly enter your HTML, CSS, and JavaScript code online, and also allows you to include the required jQuery and jQuery Mobile libraries.

### CODE REVIEW

**Comment by VaibhavPaliwal0007** [comment]
can you give a demo? or provide a URL where you have deployed your app?

**Comment by Tejaswini-052** [comment]
> can you give a demo? or provide a URL where you have deployed your app?

http://jsbin-com.stackstaging.com/
Check this link for Demo

**Review by achitJ — APPROVED** [review]
LGTM

**Review by VaibhavPaliwal0007 — APPROVED** [review]

**Comment by VaibhavPaliwal0007** [comment]
great work!!!!

**Pull request merged**
