### PR TITLE
Update README.md and made some major changes

### LINKED ISSUE #170: 🎨  Need to style README.md file
I want to add some changes in README.md file.

 📌 That includes :-
▶️ Adding some style.
▶️ Making it user friendly.
.
.
Pls assign this issue to me.

### PR DESCRIPTION
**Pull request by pratyaksh1610**
📍 Resolves #170 

🏷️ I have made some major changes in the README.md file.

⏩ Improved the style.
⏩ Made it user friendly.
⏩ Improved documentation.

I have also added an image in<b><b> .png</b></b> format.

Kindly review my PR.
Thankyou!!

h1
h2
h3

### CODE REVIEW

**Comment by VaibhavPaliwal0007** [comment]
Share the screenshots

**Comment by VaibhavPaliwal0007** [comment]
Nicely created!!

**Review by VaibhavPaliwal0007 — APPROVED** [review]

**Review by achitJ — APPROVED** [review]
Awesome work!

**Review by budhirajamadhav — APPROVED** [review]
Sexy!

**Comment by pratyaksh1610** [comment]
Open source is ❤️

**Pull request merged**
