### PR TITLE
Added Grocery Web application

### PR DESCRIPTION
**Pull request by saisumanthkumar**
This grocery web application is made with react, so i have added a react folder under frontend, and added this project

### CODE REVIEW

**Comment by VaibhavPaliwal0007** [comment]
Can you provide some screenshots or the link to the URL where the website has been deployed.

**Comment by saisumanthkumar** [comment]
@VaibhavPaliwal0007 It's there in README file

**Review by VaibhavPaliwal0007 — APPROVED** [review]

**Comment by VaibhavPaliwal0007** [comment]
Great Work!!!

**Comment by saisumanthkumar** [comment]
thank you !! 😄

**Review by budhirajamadhav — APPROVED** [review]
LGTM!

**Review by achitJ — APPROVED** [review]

**Pull request merged**
