### PR TITLE
Text-Editor

### PR DESCRIPTION
**Pull request by soniyakaramchandani42510**
A react based project
It can convert text to lowercase, uppercase ,count number of words , number of character and time to read the text.

PLEASE REVIEW IT!

### CODE REVIEW

**Comment by VaibhavPaliwal0007** [comment]
Do share the url where you have deployed your app or screenshots. Kiindly write resolve issue #issueno to link your issue with the PR.

**Comment by soniyakaramchandani42510** [comment]
> Do share the url where you have deployed your app or screenshots. Kindly write resolve issue #issueno to link your issue with the PR.
resolve issue #42

**Comment by soniyakaramchandani42510** [comment]
Screenshot (397)
Screenshot (396)

**Comment by soniyakaramchandani42510** [comment]
> Do share the url where you have deployed your app or screenshots. Kindly write resolve issue #issueno to link your issue with the PR.
Screenshot (396)
Screenshot (397)

**Comment by VaibhavPaliwal0007** [comment]
LGTM

**Review by VaibhavPaliwal0007 — APPROVED** [review]

**Pull request merged**
