### PR TITLE
Added Bookshelf App from my repository

### PR DESCRIPTION
**Pull request by alfaniM**
I have added a bookshelf

1. Which application to record the results of reading our books
2. I use Js, HTML, CSS and localstorage

### CODE REVIEW

**Comment by ij007** [comment]
Please host the app on web or attach the required screenshots to verify.

**Comment by alfaniM** [comment]
here is the screenshots 
index html

**Comment by alfaniM** [comment]
> here is the screenshots and hosted app link https://project-bookshelf-app.netlify.app index html

**Comment by alfaniM** [comment]
> Please host the app on web or attach the required screenshots to verify.

here is the screenshots and hosted app link
https://project-bookshelf-app.netlify.app
index html

**Review by achitJ — APPROVED** [review]
Good Work

**Pull request merged**
