### PR TITLE
Queue.cpp added

### LINKED ISSUE #372: Queue.cpp is added in Cpp DSA part
Added a program of using Queue as an Array in DSA part of CPP folder

### PR DESCRIPTION
**Pull request by sangraaradhya12**
Created a program of Queue as an Array and performed Menu-driven operations like Insertion, Deletion, and Display of all elements in Queue.

### CODE REVIEW

**Comment by sangraaradhya12** [comment]
@achitJ @VaibhavPaliwal0007 plz see to this PR

**Comment by sangraaradhya12** [comment]
The issue is #372

**Comment by sangraaradhya12** [comment]
@ij007

**Comment by ij007** [comment]
Sorry, but we are not accepting basic DSA problems.

**Comment by sangraaradhya12** [comment]
@ij007 but you did not mention hacktoberfest tags in my PRs what was the problem ???

**Pull request closed without merging**
